packaging_format = 2

id = "simplex"
name = "SimpleX"
description.en = "Messaging platform operating without user identifiers"
description.fr = "Plate-forme de messagerie fonctionnant sans identifiants d'utilisateurs"

version = "6.3.2~ynh1"

maintainers = []

[upstream]
license = "AGPL-3.0"
website = "https://simplex.chat/"
admindoc = "https://github.com/simplex-chat/simplex-chat/blob/stable/docs/SERVER.md"
code = "https://github.com/simplex-chat/simplexmq"
cpe = "cpe:2.3:a:simplex:simplex_chat"
fund = "https://opencollective.com/simplex-chat"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = ["amd64", "arm64"]
multi_instance = false

ldap = "not_relevant"
sso = "not_relevant"

disk = "50M"
ram.build = "150M"
ram.runtime = "50M"

[install]

[resources]

 [resources.sources]
    [resources.sources.main]
    amd64.url = "https://github.com/YunoHost-Apps/simplex_ynh/releases/download/v6.3.2/smp-server_amd64"
    amd64.sha256 = "56f690e41bed80b41674113cc3ea4bb20d91cbbbd86e01b1dc61afcb11cdc832"
    arm64.url = "https://github.com/YunoHost-Apps/simplex_ynh/releases/download/v6.3.2/smp-server_arm64"
    arm64.sha256 = "7d5c45ab65362c1bbcfb2e9790259231f17a1aa6daa75c7b0eb700b7642bd7ad"
    in_subdir = false
    extract   = false
    rename    = "smp-server"

    [resources.sources.xftp]
    amd64.url = "https://github.com/YunoHost-Apps/simplex_ynh/releases/download/v6.3.2/xftp-server_amd64"
    amd64.sha256 = "811735a3d1c0c1d690d2f6365293c7232864e224fb868dc87eb2fc4fda81021c"
    arm64.url = "https://github.com/YunoHost-Apps/simplex_ynh/releases/download/v6.3.2/xftp-server_arm64"
    arm64.sha256 = "c6480e4c9a15bd8d25688f877a40de48715412745afe48679621eb3bbce90984"
    in_subdir = false
    extract   = false
    rename    = "xftp-server"

    [resources.ports]
    main.default = 5223
    main.exposed = "TCP"
    xftp.default = 5224
    xftp.exposed = "TCP"

    [resources.system_user]

    [resources.install_dir]
    dir = "/usr/local/bin/__APP__"

    [resources.data_dir]

    [resources.permissions]
