packaging_format = 2

id = "simplex"
name = "SimpleX"
description.en = "Messaging platform operating without user identifiers"
description.fr = "Plate-forme de messagerie fonctionnant sans identifiants d'utilisateurs"

version = "6.4.1~ynh1"

maintainers = []

[upstream]
license = "AGPL-3.0"
website = "https://simplex.chat/"
admindoc = "https://github.com/simplex-chat/simplex-chat/blob/stable/docs/SERVER.md"
code = "https://github.com/simplex-chat/simplexmq"
cpe = "cpe:2.3:a:simplex:simplex_chat"
fund = "https://opencollective.com/simplex-chat"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = ["amd64", "arm64"]
multi_instance = false

ldap = "not_relevant"
sso = "not_relevant"

disk = "50M"
ram.build = "150M"
ram.runtime = "50M"

[install]

    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/simplex"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

 [resources.sources]
    [resources.sources.main]
    amd64.url = "https://github.com/YunoHost-Apps/simplex_ynh/releases/download/v6.4.1/smp-server_amd64"
    amd64.sha256 = "da7fc90473b339fa83f3ad61b257c83e4a233f6ce5d5688fd0272be2751c8d36"
    arm64.url = "https://github.com/YunoHost-Apps/simplex_ynh/releases/download/v6.4.1/smp-server_arm64"
    arm64.sha256 = "c67d78fa3bc9c9e51e461990efdb2936ec0a4cedc3751a68d761df4255d1d004"
    in_subdir = false
    extract   = false
    rename    = "smp-server"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]

    [resources.ports]
    main.default = 5223
    main.exposed = "TCP"
    main.default = 8001
