#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

#storage_quota="20gb"
#ynh_app_setting_set --key=storage_quota --value=$storage_quota

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

mkdir -p /etc/opt/simplex /var/opt/simplex
chown -R $app:$app /etc/opt/simplex /var/opt/simplex

chmod +x $install_dir/smp-server

#=================================================
# SPECIFIC SETUP
#=================================================

public_ip4="$(curl -s https://ip.yunohost.org)" || true
ynh_app_setting_set --key=public_ip4 --value=$public_ip4

pushd "$install_dir"
	ynh_hide_warnings ynh_exec_as_app ./smp-server init -y -l --no-password -n $domain #--ip $public_ip4
popd

fingerprint=$(cat /etc/opt/simplex/fingerprint)
ynh_app_setting_set --key=fingerprint --value=$fingerprint

chown -R $app:$app "/etc/opt/simplex"

#=================================================
# ADD A CONFIGURATION
#=================================================
#ynh_script_progression "Adding $app's configuration..."

ynh_config_add --template="smp-server.ini" --destination="/etc/opt/simplex/smp-server.ini"

chown $app:$app "/etc/opt/simplex/smp-server.ini"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add $app --description="Messaging platform" --log="/var/log/$app/$app.log" --needs_exposed_ports="$port"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action="start" --log_path="systemd"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
